name: Spring Boot CI/CD Java21 Docker

on:
  push:
    branches: ["main"]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Debug arborescence (Regardez bien le résultat de cette étape dans GitHub !)
      - name: Show structure
        run: ls -R

      # 3️⃣ Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 4️⃣ Build Maven (Correction : 'demo' en minuscules)
      - name: Build with Maven
        run: mvn -f demo/pom.xml clean verify

      # 5️⃣ Login DockerHub
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6️⃣ Build Docker image (Correction : 'demo' en minuscules)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-hexagonal:latest ecommerce-hexagonal

      # 7️⃣ Push image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-hexagonal:latest
